"""
Example: Afkeurbewijzen (Rejection Certificates)
==================================================
This is a reference example showing the data format expected by
the DocumentGenerator and FlowchartGenerator.

Use this as a template when creating data dictionaries for new processes.

Run this file to generate example output:
    cd project-document-agent
    python examples/afkeurbewijzen_example.py
"""

import sys
import os

# Add parent directory to path so we can import agent modules
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from agent.flowchart_generator import FlowchartGenerator
from agent.document_generator import DocumentGenerator


# ══════════════════════════════════════════════════════════
# DOCUMENT DATA
# This is the format the agent produces from conversations.
# ══════════════════════════════════════════════════════════

PROCESS_DATA = {
    "process_name": "Afkeurbewijzen",
    "process_description": "Rejection Certificate Distribution Process",
    "process_owner": "Farming Team",
    "department": "Group Business Services",

    "executive_summary": (
        "This document presents the Standardization Checkpoint analysis for the "
        "Afkeurbewijzen (Rejection Certificates) process. The analysis was conducted "
        "following the Intelligent Automation Roadmap methodology, covering SIPOC "
        "analysis, AS-IS process mapping, and baseline measurement.\n\n"
        "The Afkeurbewijzen process involves the daily distribution of individual "
        "rejection certificates to approximately 20 farmers. A consolidated PDF is "
        "generated by the ERP system (SAP) and arrives in a central mailbox at 19:00. "
        "A mid-level employee manually splits the PDF, saves individual files, looks up "
        "email addresses in SAP, and sends each file via Outlook. The process consumes "
        "approximately 636 hours per year and carries significant confidential data "
        "leakage risk.\n\n"
        "All standardization checkpoint criteria have been met. This process is "
        "recommended to proceed to the Optimization phase."
    ),

    "sipoc": {
        "suppliers": "ERP System (SAP) \u2014 auto-generates consolidated PDF daily",
        "inputs": "Daily consolidated PDF with rejection certificates; Email trigger to central mailbox at 19:00",
        "process": "1. Check mailbox\n2. Open in Adobe\n3. Split per farmer\n4. Save files\n5. Look up email in SAP\n6. Send via Outlook\n7. Print/post if no email",
        "outputs": "Individual rejection certificate PDFs per farmer; Archived files on shared drive",
        "customers": "~20 farmers per day (livestock suppliers)",
    },

    "context": {
        "Process Owner": "Farming Team",
        "Organization": "Group Business Services (Shared Service Center), reports to CFO",
        "Frequency": "Daily, 6 days per week (Sunday off) \u2014 ~312 days/year",
        "Systems & Tools": "SAP (ERP), Adobe Acrobat, Microsoft Outlook, Shared team drive",
        "Staffing": "1 mid-level employee performs this task daily",
        "Timing": "PDF arrives at 19:00 \u2014 work performed outside normal business hours",
        "Known Exceptions": "1. Manual ERP trigger if PDF late\n2. Multi-page farmers grouped visually\n3. Missing email: print and post",
    },

    "process_steps": [
        ["1", "Check central mailbox", "Farming employee", "Outlook", "\u2014", "\u2014", "1 min"],
        ["2", "Open consolidated PDF", "Farming employee", "Adobe", "\u2014", "\u2014", "1 min"],
        ["3", "Split PDF per farmer", "Farming employee", "Adobe", "New farmer? (UBN)", "Tedious; error risk", "2\u20133 min/farmer"],
        ["4", "Save individual files", "Farming employee", "Shared drive", "\u2014", "Naming error risk", "30 sec/farmer"],
        ["5", "Look up email in SAP", "Farming employee", "SAP", "Email found?", "Multi-step navigation", "1\u20132 min/farmer"],
        ["6", "Send PDF via email", "Farming employee", "Outlook", "\u2014", "\u2014", "30 sec/farmer"],
        ["6a", "Print and post (exception)", "Farming employee", "Printer/Mail", "\u2014", "Delivery delay", "5 min/farmer"],
    ],

    "baseline_metrics": [
        ["Time per process run", "100\u2013200 min (5\u201310 min \u00d7 20 farmers)", "Per day"],
        ["Frequency", "6 days per week", "~312 days/year"],
        ["Weekly time investment", "~12 hours/week", "Regular processing"],
        ["Annual time investment", "~624 hours/year", "Regular processing"],
        ["Annual rework time", "~12 hours/year", "~1 error/month \u00d7 1 hour"],
        ["Total annual effort", "~636 hours/year", "Combined"],
        ["Employee level", "Mid-level administrative", "Shared Service Center"],
        ["Error/rework rate", "~Once per month", "Wrong file to wrong farmer"],
        ["Risk impact", "HIGH \u2014 Confidential data leakage", "Competitor info shared"],
        ["SLA", "Same-day delivery required", "PDF arrives at 19:00"],
        ["Work-life balance", "Evening work required", "Outside business hours"],
    ],

    "baseline_summary": (
        "Total annual processing: 624 hours (regular) + 12 hours (rework) = "
        "636 hours/year. The process carries disproportionate risk \u2014 a single "
        "error creates confidential data exposure with compliance, legal, and "
        "reputational consequences."
    ),

    "pain_points": [
        ["1", "Evening work required", "PDF arrives at 19:00", "Work-life balance", "HIGH"],
        ["2", "Data leakage risk", "Wrong PDF to competitor", "Compliance, legal", "CRITICAL"],
        ["3", "Tedious manual work", "Repetitive splitting/sending", "Focus drops, errors", "MEDIUM"],
        ["4", "Multi-step SAP lookup", "Multiple screens per farmer", "Time waste", "LOW"],
    ],

    "statistics": [
        ["Total process steps", "7 (including 1 exception path)"],
        ["Decision points", "4"],
        ["Handoffs", "1 (System to Employee)"],
        ["Systems involved", "4 (SAP, Adobe, Outlook, Shared Drive)"],
        ["Daily volume", "~20 farmers"],
        ["Annual volume", "~6,240 farmers"],
        ["Time per farmer", "5\u201310 minutes"],
        ["Annual processing time", "636 hours"],
        ["Error frequency", "~1 per month"],
        ["Automation potential", "HIGH \u2014 structured PDF, consistent format, rule-based logic"],
    ],

    "gate_criteria": [
        ["Single process defined", "COMPLETE", "Daily rejection certificate distribution"],
        ["Known exceptions documented", "COMPLETE", "3 exceptions identified"],
        ["Stable baseline established", "COMPLETE", "636 hours/year, ~1 error/month"],
        ["SIPOC completed", "COMPLETE", "All 10 fields captured"],
        ["AS-IS process map created", "COMPLETE", "7 steps with decision points"],
        ["Baseline measurements recorded", "COMPLETE", "Time, cost, risk, SLA documented"],
    ],

    "next_steps": [
        "Eliminate manual PDF splitting through automated parsing",
        "Automate farmer email lookup from SAP",
        "Automate email distribution with standard template",
        "Resolve 19:00 timing constraint through full automation",
        "Eliminate data leakage risk through deterministic splitting",
    ],

    "signoff_roles": ["Process Owner", "Business Analyst", "Team Lead"],
}


# ══════════════════════════════════════════════════════════
# FLOWCHART DATA
# This defines the visual process flow diagram layout.
# ══════════════════════════════════════════════════════════

FLOWCHART_DATA = {
    "process_name": "Afkeurbewijzen",
    "subtitle": "Rejection Certificate Distribution  |  Farming Team  |  Daily Process",
    "swimlanes": ["System", "Employee"],

    "nodes": [
        {"id": "start", "type": "start", "text": "ERP Generates PDF",
         "lane": 0, "row": 0},
        {"id": "email", "type": "process", "lane": 0, "row": 1,
         "lines": ["PDF sent to central", "mailbox at 19:00"]},
        {"id": "check", "type": "process", "lane": 1, "row": 2,
         "lines": ["Check central mailbox", "for daily PDF"]},
        {"id": "open", "type": "process", "lane": 1, "row": 3,
         "lines": ["Open PDF in", "Adobe Acrobat"]},
        {"id": "review", "type": "process", "text": "Review page",
         "lane": 1, "row": 4},
        {"id": "d_farmer", "type": "decision", "text": "New farmer? (UBN)",
         "lane": 1, "row": 5},
        {"id": "cut", "type": "process", "lane": 1, "row": 5, "x_offset": 400,
         "width": 260, "lines": ["Cut page \u2014", "start new file"]},
        {"id": "add", "type": "process", "lane": 1, "row": 5, "x_offset": -400,
         "width": 260, "lines": ["Add page to", "current file"]},
        {"id": "save", "type": "process", "lane": 1, "row": 7,
         "width": 360, "height": 65,
         "lines": ["Save: FarmerName_UBN_Date.pdf", "(Shared drive / day folder)"]},
        {"id": "d_pages", "type": "decision", "text": "More pages in PDF?",
         "lane": 1, "row": 8},
        {"id": "lookup", "type": "process", "lane": 1, "row": 10,
         "width": 360, "height": 65,
         "lines": ["Look up farmer email in SAP", "(Farmer > Details > Communications)"]},
        {"id": "d_email", "type": "decision", "text": "Email found in SAP?",
         "lane": 1, "row": 11, "color": "#C0392B"},
        {"id": "send", "type": "process", "lane": 1, "row": 11, "x_offset": 380,
         "width": 280, "lines": ["Send PDF via Outlook", "(Standard template)"]},
        {"id": "post", "type": "exception", "lane": 1, "row": 11, "x_offset": -380,
         "width": 280, "height": 65,
         "lines": ["EXCEPTION: Print", "and send by post"]},
        {"id": "d_farmers", "type": "decision", "text": "More farmers to send?",
         "lane": 1, "row": 13},
        {"id": "archive", "type": "process", "lane": 1, "row": 15,
         "width": 360, "lines": ["Archive all files on", "shared team drive"]},
        {"id": "end", "type": "end", "text": "END \u2014 All farmers notified",
         "lane": 1, "row": 16},
    ],

    "connections": [
        {"from_id": "start", "to_id": "email", "type": "straight"},
        {"from_id": "email", "to_id": "check", "type": "right_down"},
        {"from_id": "check", "to_id": "open", "type": "straight"},
        {"from_id": "open", "to_id": "review", "type": "straight"},
        {"from_id": "review", "to_id": "d_farmer", "type": "straight"},
        {"from_id": "d_farmer", "to_id": "cut", "type": "horizontal_right", "label": "Yes"},
        {"from_id": "d_farmer", "to_id": "add", "type": "horizontal_left", "label": "No", "label_side": "above"},
        {"from_id": "save", "to_id": "d_pages", "type": "straight"},
        {"from_id": "d_pages", "to_id": "lookup", "type": "straight", "label": "No", "label_side": "left"},
        {"from_id": "d_pages", "to_id": "review", "type": "loop_right",
         "label": "Yes", "loop_x": 1700, "target_x": 1360},
        {"from_id": "lookup", "to_id": "d_email", "type": "straight"},
        {"from_id": "d_email", "to_id": "send", "type": "horizontal_right", "label": "Yes"},
        {"from_id": "d_email", "to_id": "post", "type": "horizontal_left", "label": "No", "label_side": "above"},
        {"from_id": "d_farmers", "to_id": "archive", "type": "straight", "label": "No", "label_side": "left"},
        {"from_id": "d_farmers", "to_id": "lookup", "type": "loop_left",
         "label": "Yes", "label_side": "above", "loop_x": 650, "target_x": 1020},
        {"from_id": "archive", "to_id": "end", "type": "straight"},
    ],

    "pain_points": [
        "Evening work (19:00 start)",
        "Data leakage risk",
        "Tedious manual work",
        "Multi-step SAP lookup",
    ],
}


if __name__ == "__main__":
    os.makedirs("outputs", exist_ok=True)

    # Generate flowchart
    print("Generating example flowchart...")
    fc = FlowchartGenerator()
    flowchart_path = "outputs/Example_Afkeurbewijzen_Flow.png"
    fc.generate(FLOWCHART_DATA, flowchart_path)
    print(f"  \u2713 {flowchart_path}")

    # Generate document
    print("Generating example document...")
    doc_gen = DocumentGenerator()
    doc_path = "outputs/Example_Afkeurbewijzen_Checkpoint.docx"
    doc_gen.generate(PROCESS_DATA, flowchart_path, doc_path)
    print(f"  \u2713 {doc_path}")

    print("\nDone! Example files generated in outputs/")
